# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseuse.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import userlog
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 632)
        #self.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 90, 141, 121))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 250, 93, 28))
        self.pushButton.setObjectName("pushButton")
        #self.pushButton.clicked.connect(self.clickButton)

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 360, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        #self.pushButton_2.clicked.connect(self.clickButton_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "身份选择"))
        self.label.setText(_translate("Dialog", "请选择身份"))
        self.pushButton.setText(_translate("Dialog", "管理员"))
        self.pushButton_2.setText(_translate("Dialog", "用户"))

