# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import gogogo
username=""
pas=""

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        global username
        global password
        Dialog.setObjectName("Dialog")
        Dialog.resize(322, 657)
        #self.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint)


        #提交
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 480, 101, 32))
        self.pushButton.setObjectName("pushButton")

        # 登录
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(100, 350, 101, 32))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_1.clicked.connect(self.clickButton)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 100, 111, 51))
        self.label.setObjectName("label")


        self.user = QtWidgets.QTextEdit(Dialog)
        self.user.setGeometry(QtCore.QRect(110, 210, 171, 31))
        self.user.setObjectName("user")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 220, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 290, 72, 15))
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QTextEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(110, 280, 171, 31))
        self.password.setObjectName("password")

        self.retranslateUi(Dialog)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "请登录"))
        self.label.setText(_translate("Dialog", "管理员登录"))
        self.label_2.setText(_translate("Dialog", "请输入用户名"))
        self.label_3.setText(_translate("Dialog", "密码"))
        self.pushButton.setText(_translate("Dialog", "进入"))
        self.pushButton_1.setText(_translate("Dialog", "登录"))

    def clickButton(self):
        # global pas
        # global username
        # username=self.user.text()
        # print(username)
        # pas=self.password.text()
        # print(pas)
        pass
