# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("请选择座位")
        Dialog.resize(722, 610)
        self.pushButton01 = QtWidgets.QPushButton(Dialog)
        self.pushButton01.setGeometry(QtCore.QRect(70, 60, 41, 41))
        self.pushButton01.setObjectName("pushButton01")
        self.pushButton01.setStyleSheet('''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.pushButton01.clicked.connect(self.clickButton)


        self.pushButton_02 = QtWidgets.QPushButton(Dialog)
        self.pushButton_02.setGeometry(QtCore.QRect(130, 60, 41, 41))
        self.pushButton_02.setObjectName("pushButton_02")
        self.pushButton_02.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_03 = QtWidgets.QPushButton(Dialog)
        self.pushButton_03.setGeometry(QtCore.QRect(190, 60, 41, 41))
        self.pushButton_03.setObjectName("pushButton_03")
        self.pushButton_03.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_04 = QtWidgets.QPushButton(Dialog)
        self.pushButton_04.setGeometry(QtCore.QRect(250, 60, 41, 41))
        self.pushButton_04.setObjectName("pushButton_04")
        self.pushButton_04.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_05 = QtWidgets.QPushButton(Dialog)
        self.pushButton_05.setGeometry(QtCore.QRect(320, 60, 41, 41))
        self.pushButton_05.setObjectName("pushButton_05")
        self.pushButton_05.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_06 = QtWidgets.QPushButton(Dialog)
        self.pushButton_06.setGeometry(QtCore.QRect(400, 60, 41, 41))
        self.pushButton_06.setObjectName("pushButton_06")
        self.pushButton_06.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_07 = QtWidgets.QPushButton(Dialog)
        self.pushButton_07.setGeometry(QtCore.QRect(460, 60, 41, 41))
        self.pushButton_07.setObjectName("pushButton_07")
        self.pushButton_07.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_08 = QtWidgets.QPushButton(Dialog)
        self.pushButton_08.setGeometry(QtCore.QRect(530, 60, 41, 41))
        self.pushButton_08.setObjectName("pushButton_08")
        self.pushButton_08.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_09 = QtWidgets.QPushButton(Dialog)
        self.pushButton_09.setGeometry(QtCore.QRect(590, 60, 41, 41))
        self.pushButton_09.setObjectName("pushButton_09")
        self.pushButton_09.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(70, 120, 41, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 120, 41, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(190, 120, 41, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(250, 120, 41, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(320, 120, 41, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(400, 120, 41, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(460, 120, 41, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_17 = QtWidgets.QPushButton(Dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(530, 120, 41, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_18 = QtWidgets.QPushButton(Dialog)
        self.pushButton_18.setGeometry(QtCore.QRect(590, 120, 41, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_18.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_19 = QtWidgets.QPushButton(Dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(70, 180, 41, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(130, 180, 41, 41))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(190, 180, 41, 41))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(250, 180, 41, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_22.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(320, 180, 41, 41))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_23.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_24 = QtWidgets.QPushButton(Dialog)
        self.pushButton_24.setGeometry(QtCore.QRect(400, 180, 41, 41))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_24.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.pushButton_25 = QtWidgets.QPushButton(Dialog)
        self.pushButton_25.setGeometry(QtCore.QRect(460, 180, 41, 41))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_25.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_26 = QtWidgets.QPushButton(Dialog)
        self.pushButton_26.setGeometry(QtCore.QRect(530, 180, 41, 41))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_26.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_27 = QtWidgets.QPushButton(Dialog)
        self.pushButton_27.setGeometry(QtCore.QRect(590, 180, 41, 41))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_27.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_28 = QtWidgets.QPushButton(Dialog)
        self.pushButton_28.setGeometry(QtCore.QRect(70, 240, 41, 41))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_28.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_29 = QtWidgets.QPushButton(Dialog)
        self.pushButton_29.setGeometry(QtCore.QRect(130, 240, 41, 41))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_29.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_30 = QtWidgets.QPushButton(Dialog)
        self.pushButton_30.setGeometry(QtCore.QRect(190, 240, 41, 41))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_30.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_31 = QtWidgets.QPushButton(Dialog)
        self.pushButton_31.setGeometry(QtCore.QRect(250, 240, 41, 41))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_31.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_32 = QtWidgets.QPushButton(Dialog)
        self.pushButton_32.setGeometry(QtCore.QRect(320, 240, 41, 41))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_32.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_33 = QtWidgets.QPushButton(Dialog)
        self.pushButton_33.setGeometry(QtCore.QRect(400, 240, 41, 41))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_33.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_34 = QtWidgets.QPushButton(Dialog)
        self.pushButton_34.setGeometry(QtCore.QRect(460, 240, 41, 41))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_34.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_35 = QtWidgets.QPushButton(Dialog)
        self.pushButton_35.setGeometry(QtCore.QRect(530, 240, 41, 41))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_35.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_36 = QtWidgets.QPushButton(Dialog)
        self.pushButton_36.setGeometry(QtCore.QRect(590, 240, 41, 41))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_36.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_37 = QtWidgets.QPushButton(Dialog)
        self.pushButton_37.setGeometry(QtCore.QRect(70, 300, 41, 41))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_37.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_38 = QtWidgets.QPushButton(Dialog)
        self.pushButton_38.setGeometry(QtCore.QRect(130, 300, 41, 41))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_38.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_39 = QtWidgets.QPushButton(Dialog)
        self.pushButton_39.setGeometry(QtCore.QRect(190, 300, 41, 41))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_39.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_40 = QtWidgets.QPushButton(Dialog)
        self.pushButton_40.setGeometry(QtCore.QRect(250, 300, 41, 41))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_40.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_41 = QtWidgets.QPushButton(Dialog)
        self.pushButton_41.setGeometry(QtCore.QRect(320, 300, 41, 41))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_41.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_42 = QtWidgets.QPushButton(Dialog)
        self.pushButton_42.setGeometry(QtCore.QRect(400, 300, 41, 41))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_42.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_43 = QtWidgets.QPushButton(Dialog)
        self.pushButton_43.setGeometry(QtCore.QRect(460, 300, 41, 41))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_43.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_44 = QtWidgets.QPushButton(Dialog)
        self.pushButton_44.setGeometry(QtCore.QRect(530, 300, 41, 41))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_44.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.pushButton_45 = QtWidgets.QPushButton(Dialog)
        self.pushButton_45.setGeometry(QtCore.QRect(590, 300, 41, 41))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_45.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_46 = QtWidgets.QPushButton(Dialog)
        self.pushButton_46.setGeometry(QtCore.QRect(70, 360, 41, 41))
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_46.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_47 = QtWidgets.QPushButton(Dialog)
        self.pushButton_47.setGeometry(QtCore.QRect(130, 360, 41, 41))
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_47.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_48 = QtWidgets.QPushButton(Dialog)
        self.pushButton_48.setGeometry(QtCore.QRect(190, 360, 41, 41))
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_48.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_49 = QtWidgets.QPushButton(Dialog)
        self.pushButton_49.setGeometry(QtCore.QRect(250, 360, 41, 41))
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_49.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_50 = QtWidgets.QPushButton(Dialog)
        self.pushButton_50.setGeometry(QtCore.QRect(320, 360, 41, 41))
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_50.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_51 = QtWidgets.QPushButton(Dialog)
        self.pushButton_51.setGeometry(QtCore.QRect(400, 360, 41, 41))
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_51.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_52 = QtWidgets.QPushButton(Dialog)
        self.pushButton_52.setGeometry(QtCore.QRect(460, 360, 41, 41))
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_52.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_53 = QtWidgets.QPushButton(Dialog)
        self.pushButton_53.setGeometry(QtCore.QRect(530, 360, 41, 41))
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_53.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_54 = QtWidgets.QPushButton(Dialog)
        self.pushButton_54.setGeometry(QtCore.QRect(590, 360, 41, 41))
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_54.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(440, 520, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 520, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def clickButton(self):
        sender = self.sender()
        print(sender.text() + '被点击')


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "请选择座位"))
        self.pushButton01.setText(_translate("Dialog", "1"))
        self.pushButton_02.setText(_translate("Dialog", "2"))
        self.pushButton_03.setText(_translate("Dialog", "3"))
        self.pushButton_04.setText(_translate("Dialog", "4"))
        self.pushButton_05.setText(_translate("Dialog", "5"))
        self.pushButton_06.setText(_translate("Dialog", "6"))
        self.pushButton_07.setText(_translate("Dialog", "7"))
        self.pushButton_08.setText(_translate("Dialog", "8"))
        self.pushButton_09.setText(_translate("Dialog", "9"))
        self.pushButton_10.setText(_translate("Dialog", "10"))
        self.pushButton_11.setText(_translate("Dialog", "11"))
        self.pushButton_12.setText(_translate("Dialog", "12"))
        self.pushButton_13.setText(_translate("Dialog", "13"))
        self.pushButton_14.setText(_translate("Dialog", "14"))
        self.pushButton_15.setText(_translate("Dialog", "15"))
        self.pushButton_16.setText(_translate("Dialog", "16"))
        self.pushButton_17.setText(_translate("Dialog", "17"))
        self.pushButton_18.setText(_translate("Dialog", "18"))
        self.pushButton_19.setText(_translate("Dialog", "19"))
        self.pushButton_20.setText(_translate("Dialog", "20"))
        self.pushButton_21.setText(_translate("Dialog", "21"))
        self.pushButton_22.setText(_translate("Dialog", "22"))
        self.pushButton_23.setText(_translate("Dialog", "23"))
        self.pushButton_24.setText(_translate("Dialog", "24"))
        self.pushButton_25.setText(_translate("Dialog", "25"))
        self.pushButton_26.setText(_translate("Dialog", "26"))
        self.pushButton_27.setText(_translate("Dialog", "27"))
        self.pushButton_28.setText(_translate("Dialog", "28"))
        self.pushButton_29.setText(_translate("Dialog", "39"))
        self.pushButton_30.setText(_translate("Dialog", "30"))
        self.pushButton_31.setText(_translate("Dialog", "31"))
        self.pushButton_32.setText(_translate("Dialog", "32"))
        self.pushButton_33.setText(_translate("Dialog", "33"))
        self.pushButton_34.setText(_translate("Dialog", "34"))
        self.pushButton_35.setText(_translate("Dialog", "35"))
        self.pushButton_36.setText(_translate("Dialog", "36"))
        self.pushButton_37.setText(_translate("Dialog", "37"))
        self.pushButton_38.setText(_translate("Dialog", "38"))
        self.pushButton_39.setText(_translate("Dialog", "39"))
        self.pushButton_40.setText(_translate("Dialog", "40"))
        self.pushButton_41.setText(_translate("Dialog", "41"))
        self.pushButton_42.setText(_translate("Dialog", "42"))
        self.pushButton_43.setText(_translate("Dialog", "43"))
        self.pushButton_44.setText(_translate("Dialog", "44"))
        self.pushButton_45.setText(_translate("Dialog", "45"))
        self.pushButton_46.setText(_translate("Dialog", "46"))
        self.pushButton_47.setText(_translate("Dialog", "47"))
        self.pushButton_48.setText(_translate("Dialog", "48"))
        self.pushButton_49.setText(_translate("Dialog", "49"))
        self.pushButton_50.setText(_translate("Dialog", "50"))
        self.pushButton_51.setText(_translate("Dialog", "51"))
        self.pushButton_52.setText(_translate("Dialog", "52"))
        self.pushButton_53.setText(_translate("Dialog", "53"))
        self.pushButton_54.setText(_translate("Dialog", "54"))
        self.pushButton.setText(_translate("Dialog", "提交"))

        self.pushButton_2.setText(_translate("Dialog", "取消"))
