# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import userwork
import userlog
import ast
list=[]
count=0
username=""
def change(a):
    global username
    username=a


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        global list
        global count

        # connect = pymysql.connect(host='localhost',  # 本地数据库
        #                           user='root',
        #                           password='gzy158',
        #                           db='课程设计',
        #                           charset='utf8')  # 服务器名,账户,密码，数据库名称
        # cur = connect.cursor()
        # val=(userwork.getday(),userwork.gettime())
        # print(val)
        # cur.execute("""
        # select * from seat
        # where date=%s,time=%s
        # """,val)

        Dialog.setObjectName("请选择座位")
        Dialog.resize(722, 610)
        self.pushButton_01 = QtWidgets.QPushButton(Dialog)
        self.pushButton_01.setGeometry(QtCore.QRect(70, 60, 41, 41))
        self.pushButton_01.setObjectName("pushButton01")
        self.pushButton_01.setStyleSheet('''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')



        self.pushButton_02 = QtWidgets.QPushButton(Dialog)
        self.pushButton_02.setGeometry(QtCore.QRect(130, 60, 41, 41))
        self.pushButton_02.setObjectName("pushButton_02")
        self.pushButton_02.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_03 = QtWidgets.QPushButton(Dialog)
        self.pushButton_03.setGeometry(QtCore.QRect(190, 60, 41, 41))
        self.pushButton_03.setObjectName("pushButton_03")
        self.pushButton_03.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_04 = QtWidgets.QPushButton(Dialog)
        self.pushButton_04.setGeometry(QtCore.QRect(250, 60, 41, 41))
        self.pushButton_04.setObjectName("pushButton_04")
        self.pushButton_04.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_05 = QtWidgets.QPushButton(Dialog)
        self.pushButton_05.setGeometry(QtCore.QRect(320, 60, 41, 41))
        self.pushButton_05.setObjectName("pushButton_05")
        self.pushButton_05.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_06 = QtWidgets.QPushButton(Dialog)
        self.pushButton_06.setGeometry(QtCore.QRect(400, 60, 41, 41))
        self.pushButton_06.setObjectName("pushButton_06")
        self.pushButton_06.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_07 = QtWidgets.QPushButton(Dialog)
        self.pushButton_07.setGeometry(QtCore.QRect(460, 60, 41, 41))
        self.pushButton_07.setObjectName("pushButton_07")
        self.pushButton_07.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_08 = QtWidgets.QPushButton(Dialog)
        self.pushButton_08.setGeometry(QtCore.QRect(530, 60, 41, 41))
        self.pushButton_08.setObjectName("pushButton_08")
        self.pushButton_08.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_09 = QtWidgets.QPushButton(Dialog)
        self.pushButton_09.setGeometry(QtCore.QRect(590, 60, 41, 41))
        self.pushButton_09.setObjectName("pushButton_09")
        self.pushButton_09.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(70, 120, 41, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(130, 120, 41, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(190, 120, 41, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_12.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(250, 120, 41, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_13.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(320, 120, 41, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_14.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(400, 120, 41, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(460, 120, 41, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_16.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_17 = QtWidgets.QPushButton(Dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(530, 120, 41, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_17.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_18 = QtWidgets.QPushButton(Dialog)
        self.pushButton_18.setGeometry(QtCore.QRect(590, 120, 41, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_18.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_19 = QtWidgets.QPushButton(Dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(70, 180, 41, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_19.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(130, 180, 41, 41))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_20.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(190, 180, 41, 41))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_21.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(250, 180, 41, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_22.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(320, 180, 41, 41))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_23.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_24 = QtWidgets.QPushButton(Dialog)
        self.pushButton_24.setGeometry(QtCore.QRect(400, 180, 41, 41))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_24.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.pushButton_25 = QtWidgets.QPushButton(Dialog)
        self.pushButton_25.setGeometry(QtCore.QRect(460, 180, 41, 41))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_25.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_26 = QtWidgets.QPushButton(Dialog)
        self.pushButton_26.setGeometry(QtCore.QRect(530, 180, 41, 41))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_26.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_27 = QtWidgets.QPushButton(Dialog)
        self.pushButton_27.setGeometry(QtCore.QRect(590, 180, 41, 41))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_27.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_28 = QtWidgets.QPushButton(Dialog)
        self.pushButton_28.setGeometry(QtCore.QRect(70, 240, 41, 41))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_28.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_29 = QtWidgets.QPushButton(Dialog)
        self.pushButton_29.setGeometry(QtCore.QRect(130, 240, 41, 41))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_29.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_30 = QtWidgets.QPushButton(Dialog)
        self.pushButton_30.setGeometry(QtCore.QRect(190, 240, 41, 41))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_30.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_31 = QtWidgets.QPushButton(Dialog)
        self.pushButton_31.setGeometry(QtCore.QRect(250, 240, 41, 41))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_31.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_32 = QtWidgets.QPushButton(Dialog)
        self.pushButton_32.setGeometry(QtCore.QRect(320, 240, 41, 41))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_32.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_33 = QtWidgets.QPushButton(Dialog)
        self.pushButton_33.setGeometry(QtCore.QRect(400, 240, 41, 41))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_33.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_34 = QtWidgets.QPushButton(Dialog)
        self.pushButton_34.setGeometry(QtCore.QRect(460, 240, 41, 41))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_34.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_35 = QtWidgets.QPushButton(Dialog)
        self.pushButton_35.setGeometry(QtCore.QRect(530, 240, 41, 41))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_35.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_36 = QtWidgets.QPushButton(Dialog)
        self.pushButton_36.setGeometry(QtCore.QRect(590, 240, 41, 41))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_36.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_37 = QtWidgets.QPushButton(Dialog)
        self.pushButton_37.setGeometry(QtCore.QRect(70, 300, 41, 41))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_37.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_38 = QtWidgets.QPushButton(Dialog)
        self.pushButton_38.setGeometry(QtCore.QRect(130, 300, 41, 41))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_38.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_39 = QtWidgets.QPushButton(Dialog)
        self.pushButton_39.setGeometry(QtCore.QRect(190, 300, 41, 41))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_39.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_40 = QtWidgets.QPushButton(Dialog)
        self.pushButton_40.setGeometry(QtCore.QRect(250, 300, 41, 41))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_40.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_41 = QtWidgets.QPushButton(Dialog)
        self.pushButton_41.setGeometry(QtCore.QRect(320, 300, 41, 41))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_41.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_42 = QtWidgets.QPushButton(Dialog)
        self.pushButton_42.setGeometry(QtCore.QRect(400, 300, 41, 41))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_42.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_43 = QtWidgets.QPushButton(Dialog)
        self.pushButton_43.setGeometry(QtCore.QRect(460, 300, 41, 41))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_43.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_44 = QtWidgets.QPushButton(Dialog)
        self.pushButton_44.setGeometry(QtCore.QRect(530, 300, 41, 41))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_44.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.pushButton_45 = QtWidgets.QPushButton(Dialog)
        self.pushButton_45.setGeometry(QtCore.QRect(590, 300, 41, 41))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_45.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_46 = QtWidgets.QPushButton(Dialog)
        self.pushButton_46.setGeometry(QtCore.QRect(70, 360, 41, 41))
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_46.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_47 = QtWidgets.QPushButton(Dialog)
        self.pushButton_47.setGeometry(QtCore.QRect(130, 360, 41, 41))
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_47.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_48 = QtWidgets.QPushButton(Dialog)
        self.pushButton_48.setGeometry(QtCore.QRect(190, 360, 41, 41))
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_48.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_49 = QtWidgets.QPushButton(Dialog)
        self.pushButton_49.setGeometry(QtCore.QRect(250, 360, 41, 41))
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_49.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_50 = QtWidgets.QPushButton(Dialog)
        self.pushButton_50.setGeometry(QtCore.QRect(320, 360, 41, 41))
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_50.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_51 = QtWidgets.QPushButton(Dialog)
        self.pushButton_51.setGeometry(QtCore.QRect(400, 360, 41, 41))
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_51.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_52 = QtWidgets.QPushButton(Dialog)
        self.pushButton_52.setGeometry(QtCore.QRect(460, 360, 41, 41))
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_52.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_53 = QtWidgets.QPushButton(Dialog)
        self.pushButton_53.setGeometry(QtCore.QRect(530, 360, 41, 41))
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_53.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_54 = QtWidgets.QPushButton(Dialog)
        self.pushButton_54.setGeometry(QtCore.QRect(590, 360, 41, 41))
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_54.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(440, 520, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clickButton)

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 520, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.clickButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(480, 420, 93, 28))
        self.pushButton_3.setObjectName("pushButton_2")
        self.pushButton_3.clicked.connect(self.clickButton_3)

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(560, 560, 93, 28))
        self.label_2.setObjectName("label_2")


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)







    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "请选择座位"))
        self.pushButton_01.setText(_translate("Dialog", "1"))
        self.pushButton_02.setText(_translate("Dialog", "2"))
        self.pushButton_03.setText(_translate("Dialog", "3"))
        self.pushButton_04.setText(_translate("Dialog", "4"))
        self.pushButton_05.setText(_translate("Dialog", "5"))
        self.pushButton_06.setText(_translate("Dialog", "6"))
        self.pushButton_07.setText(_translate("Dialog", "7"))
        self.pushButton_08.setText(_translate("Dialog", "8"))
        self.pushButton_09.setText(_translate("Dialog", "9"))
        self.pushButton_10.setText(_translate("Dialog", "10"))
        self.pushButton_11.setText(_translate("Dialog", "11"))
        self.pushButton_12.setText(_translate("Dialog", "12"))
        self.pushButton_13.setText(_translate("Dialog", "13"))
        self.pushButton_14.setText(_translate("Dialog", "14"))
        self.pushButton_15.setText(_translate("Dialog", "15"))
        self.pushButton_16.setText(_translate("Dialog", "16"))
        self.pushButton_17.setText(_translate("Dialog", "17"))
        self.pushButton_18.setText(_translate("Dialog", "18"))
        self.pushButton_19.setText(_translate("Dialog", "19"))
        self.pushButton_20.setText(_translate("Dialog", "20"))
        self.pushButton_21.setText(_translate("Dialog", "21"))
        self.pushButton_22.setText(_translate("Dialog", "22"))
        self.pushButton_23.setText(_translate("Dialog", "23"))
        self.pushButton_24.setText(_translate("Dialog", "24"))
        self.pushButton_25.setText(_translate("Dialog", "25"))
        self.pushButton_26.setText(_translate("Dialog", "26"))
        self.pushButton_27.setText(_translate("Dialog", "27"))
        self.pushButton_28.setText(_translate("Dialog", "28"))
        self.pushButton_29.setText(_translate("Dialog", "39"))
        self.pushButton_30.setText(_translate("Dialog", "30"))
        self.pushButton_31.setText(_translate("Dialog", "31"))
        self.pushButton_32.setText(_translate("Dialog", "32"))
        self.pushButton_33.setText(_translate("Dialog", "33"))
        self.pushButton_34.setText(_translate("Dialog", "34"))
        self.pushButton_35.setText(_translate("Dialog", "35"))
        self.pushButton_36.setText(_translate("Dialog", "36"))
        self.pushButton_37.setText(_translate("Dialog", "37"))
        self.pushButton_38.setText(_translate("Dialog", "38"))
        self.pushButton_39.setText(_translate("Dialog", "39"))
        self.pushButton_40.setText(_translate("Dialog", "40"))
        self.pushButton_41.setText(_translate("Dialog", "41"))
        self.pushButton_42.setText(_translate("Dialog", "42"))
        self.pushButton_43.setText(_translate("Dialog", "43"))
        self.pushButton_44.setText(_translate("Dialog", "44"))
        self.pushButton_45.setText(_translate("Dialog", "45"))
        self.pushButton_46.setText(_translate("Dialog", "46"))
        self.pushButton_47.setText(_translate("Dialog", "47"))
        self.pushButton_48.setText(_translate("Dialog", "48"))
        self.pushButton_49.setText(_translate("Dialog", "49"))
        self.pushButton_50.setText(_translate("Dialog", "50"))
        self.pushButton_51.setText(_translate("Dialog", "51"))
        self.pushButton_52.setText(_translate("Dialog", "52"))
        self.pushButton_53.setText(_translate("Dialog", "53"))
        self.pushButton_54.setText(_translate("Dialog", "54"))
        self.pushButton.setText(_translate("Dialog", "提交"))

        self.pushButton_2.setText(_translate("Dialog", "费用"))
        self.pushButton_3.setText(_translate("Dialog", "查看座位"))

    def clickButton_01(self):
        global list
        global count
        if 1 in list:
            list.remove(1)
            self.pushButton_01.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_01.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(1)
            print(list)
            count = count + 1
            print(count)


    def clickButton_02(self):
        global list
        global count
        if 2 in list:
            list.remove(2)
            self.pushButton_02.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_02.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(2)
            print(list)
            count = count + 1
            print(count)


    def clickButton_03(self):
        global list
        global count
        if 3 in list:
            list.remove(3)
            self.pushButton_03.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_03.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(3)
            print(list)
            count = count + 1
            print(count)


    def clickButton_04(self):
        global list
        global count
        if 4 in list:
            list.remove(4)
            self.pushButton_04.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_04.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(4)
            print(list)
            count = count + 1
            print(count)


    def clickButton_05(self):
        global list
        global count
        if 5 in list:
            list.remove(5)
            self.pushButton_05.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_05.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(5)
            print(list)
            count = count + 1
            print(count)


    def clickButton_06(self):
        global list
        global count
        if 6 in list:
            list.remove(6)
            self.pushButton_06.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_06.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(6)
            print(list)
            count = count + 1
            print(count)


    def clickButton_07(self):
        global list
        global count
        if 7 in list:
            list.remove(7)
            self.pushButton_07.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_07.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(7)
            print(list)
            count = count + 1
            print(count)


    def clickButton_08(self):
        global list
        global count
        if 8 in list:
            list.remove(8)
            self.pushButton_08.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_08.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(8)
            print(list)
            count = count + 1
            print(count)


    def clickButton_09(self):
        global list
        global count
        if 9 in list:
            list.remove(9)
            self.pushButton_09.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_09.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(9)
            print(list)
            count = count + 1
            print(count)


    def clickButton_10(self):
        global list
        global count
        if 10 in list:
            list.remove(10)
            self.pushButton_10.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_10.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(10)
            print(list)
            count = count + 1
            print(count)


    def clickButton_11(self):
        global list
        global count
        if 11 in list:
            list.remove(11)
            self.pushButton_11.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_11.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(11)
            print(list)
            count = count + 1
            print(count)


    def clickButton_12(self):
        global list
        global count
        if 12 in list:
            list.remove(12)
            self.pushButton_12.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_12.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(12)
            print(list)
            count = count + 1
            print(count)


    def clickButton_13(self):
        global list
        global count
        if 13 in list:
            list.remove(13)
            self.pushButton_13.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_13.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(13)
            print(list)
            count = count + 1
            print(count)


    def clickButton_14(self):
        global list
        global count
        if 14 in list:
            list.remove(14)
            self.pushButton_14.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_14.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(14)
            print(list)
            count = count + 1
            print(count)


    def clickButton_15(self):
        global list
        global count
        if 15 in list:
            list.remove(15)
            self.pushButton_15.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_15.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(15)
            print(list)
            count = count + 1
            print(count)


    def clickButton_16(self):
        global list
        global count
        if 16 in list:
            list.remove(16)
            self.pushButton_16.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_16.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(16)
            print(list)
            count = count + 1
            print(count)


    def clickButton_17(self):
        global list
        global count
        if 17 in list:
            list.remove(17)
            self.pushButton_17.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_17.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(17)
            print(list)
            count = count + 1
            print(count)


    def clickButton_18(self):
        global list
        global count
        if 18 in list:
            list.remove(18)
            self.pushButton_18.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_18.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(18)
            print(list)
            count = count + 1
            print(count)


    def clickButton_19(self):
        global list
        global count
        if 19 in list:
            list.remove(19)
            self.pushButton_19.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_19.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(19)
            print(list)
            count = count + 1
            print(count)


    def clickButton_20(self):
        global list
        global count
        if 20 in list:
            list.remove(20)
            self.pushButton_20.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_20.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(20)
            print(list)
            count = count + 1
            print(count)


    def clickButton_21(self):
        global list
        global count
        if 21 in list:
            list.remove(21)
            self.pushButton_21.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_21.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(21)
            print(list)
            count = count + 1
            print(count)


    def clickButton_22(self):
        global list
        global count
        if 22 in list:
            list.remove(22)
            self.pushButton_22.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_22.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(22)
            print(list)
            count = count + 1
            print(count)


    def clickButton_23(self):
        global list
        global count
        if 23 in list:
            list.remove(23)
            self.pushButton_23.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_23.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(23)
            print(list)
            count = count + 1
            print(count)


    def clickButton_24(self):
        global list
        global count
        if 24 in list:
            list.remove(24)
            self.pushButton_24.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_24.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(24)
            print(list)
            count = count + 1
            print(count)


    def clickButton_25(self):
        global list
        global count
        if 25 in list:
            list.remove(25)
            self.pushButton_25.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_25.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(25)
            print(list)
            count = count + 1
            print(count)


    def clickButton_26(self):
        global list
        global count
        if 26 in list:
            list.remove(26)
            self.pushButton_26.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_26.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(26)
            print(list)
            count = count + 1
            print(count)


    def clickButton_27(self):
        global list
        global count
        if 27 in list:
            list.remove(27)
            self.pushButton_27.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_27.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(27)
            print(list)
            count = count + 1
            print(count)


    def clickButton_28(self):
        global list
        global count
        if 28 in list:
            list.remove(28)
            self.pushButton_28.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_28.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(28)
            print(list)
            count = count + 1
            print(count)


    def clickButton_29(self):
        global list
        global count
        if 29 in list:
            list.remove(29)
            self.pushButton_29.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_29.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(29)
            print(list)
            count = count + 1
            print(count)


    def clickButton_30(self):
        global list
        global count
        if 30 in list:
            list.remove(30)
            self.pushButton_30.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_30.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(30)
            print(list)
            count = count + 1
            print(count)


    def clickButton_31(self):
        global list
        global count
        if 31 in list:
            list.remove(31)
            self.pushButton_31.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_31.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(31)
            print(list)
            count = count + 1
            print(count)


    def clickButton_32(self):
        global list
        global count
        if 32 in list:
            list.remove(32)
            self.pushButton_32.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_32.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(32)
            print(list)
            count = count + 1
            print(count)


    def clickButton_33(self):
        global list
        global count
        if 33 in list:
            list.remove(33)
            self.pushButton_33.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_33.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(33)
            print(list)
            count = count + 1
            print(count)


    def clickButton_34(self):
        global list
        global count
        if 34 in list:
            list.remove(34)
            self.pushButton_34.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_34.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(34)
            print(list)
            count = count + 1
            print(count)


    def clickButton_35(self):
        global list
        global count
        if 35 in list:
            list.remove(35)
            self.pushButton_35.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_35.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(35)
            print(list)
            count = count + 1
            print(count)


    def clickButton_36(self):
        global list
        global count
        if 36 in list:
            list.remove(36)
            self.pushButton_36.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_36.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(36)
            print(list)
            count = count + 1
            print(count)


    def clickButton_37(self):
        global list
        global count
        if 37 in list:
            list.remove(37)
            self.pushButton_37.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_37.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(37)
            print(list)
            count = count + 1
            print(count)


    def clickButton_38(self):
        global list
        global count
        if 38 in list:
            list.remove(38)
            self.pushButton_38.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_38.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(38)
            print(list)
            count = count + 1
            print(count)


    def clickButton_39(self):
        global list
        global count
        if 39 in list:
            list.remove(39)
            self.pushButton_39.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_39.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(39)
            print(list)
            count = count + 1
            print(count)


    def clickButton_40(self):
        global list
        global count
        if 40 in list:
            list.remove(40)
            self.pushButton_40.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_40.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(40)
            print(list)
            count = count + 1
            print(count)


    def clickButton_41(self):
        global list
        global count
        if 41 in list:
            list.remove(41)
            self.pushButton_41.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_41.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(41)
            print(list)
            count = count + 1
            print(count)


    def clickButton_42(self):
        global list
        global count
        if 42 in list:
            list.remove(42)
            self.pushButton_42.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_42.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(42)
            print(list)
            count = count + 1
            print(count)


    def clickButton_43(self):
        global list
        global count
        if 43 in list:
            list.remove(43)
            self.pushButton_43.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_43.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(43)
            print(list)
            count = count + 1
            print(count)


    def clickButton_44(self):
        global list
        global count
        if 44 in list:
            list.remove(44)
            self.pushButton_44.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_44.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(44)
            print(list)
            count = count + 1
            print(count)


    def clickButton_45(self):
        global list
        global count
        if 45 in list:
            list.remove(45)
            self.pushButton_45.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_45.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(45)
            print(list)
            count = count + 1
            print(count)


    def clickButton_46(self):
        global list
        global count
        if 46 in list:
            list.remove(46)
            self.pushButton_46.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_46.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(46)
            print(list)
            count = count + 1
            print(count)


    def clickButton_47(self):
        global list
        global count
        if 47 in list:
            list.remove(47)
            self.pushButton_47.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_47.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(47)
            print(list)
            count = count + 1
            print(count)


    def clickButton_48(self):
        global list
        global count
        if 48 in list:
            list.remove(48)
            self.pushButton_48.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_48.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(48)
            print(list)
            count = count + 1
            print(count)


    def clickButton_49(self):
        global list
        global count
        if 49 in list:
            list.remove(49)
            self.pushButton_49.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_49.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(49)
            print(list)
            count = count + 1
            print(count)


    def clickButton_50(self):
        global list
        global count
        if 50 in list:
            list.remove(50)
            self.pushButton_50.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_50.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(50)
            print(list)
            count = count + 1
            print(count)


    def clickButton_51(self):
        global list
        global count
        if 51 in list:
            list.remove(51)
            self.pushButton_51.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_51.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(51)
            print(list)
            count = count + 1
            print(count)


    def clickButton_52(self):
        global list
        global count
        if 52 in list:
            list.remove(52)
            self.pushButton_52.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_52.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(52)
            print(list)
            count = count + 1
            print(count)


    def clickButton_53(self):
        global list
        global count
        if 53 in list:
            list.remove(53)
            self.pushButton_53.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_53.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(53)
            print(list)
            count = count + 1
            print(count)


    def clickButton_54(self):
        global list
        global count
        if 54 in list:
            list.remove(54)
            self.pushButton_54.setStyleSheet(
                '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')
            count = count - 1
            print(count)
        else:
            self.pushButton_54.setStyleSheet(
                '''QPushButton{background:#FFFF00;border-radius:5px;}QPushButton:hover{background:yellow;}''')
            list.append(54)
            print(list)
            count = count + 1
            print(count)

    #订票
    def clickButton(self):
        global list
        global username
        connect = pymysql.connect(host='localhost',  # 本地数据库
                                  user='root',
                                  password='gzy158',
                                  db='课程设计',
                                  charset='utf8')  # 服务器名,账户,密码，数据库名称
        cur = connect.cursor()
        val0=(userwork.getday(),userwork.gettime())
        cur.execute("""
                        select * from seat
                        where date=%s and time=%s
                        """, val0)
        for row in cur.fetchall():
            a=int(row[3])
        a=a-count
        val = (str(list),str(a),str(userwork.getday()),str(userwork.gettime()))
        cur.execute("""
                update seat
                set seat=%s,count=%s
                where date=%s and time=%s
                """, val)

        val3=(username,userwork.getday(),userwork.gettime(),count)

        cur.execute("""
                        insert into seachorder(username,day,time,count)
                        values
                        (%s,%s,%s,%s)
                        """, val3)


        temp=""
        cur.execute("""
                        select * from user
                        where username=%s
                        """,username)
        for row in cur.fetchall():
            temp=row[3]
        list1=ast.literal_eval(temp)
        a=str((str(userwork.getday()),str(userwork.gettime()),str(list)))
        print(a)
        list1.append(a)

        print(username)
        val1=(str(list1),username)
        cur.execute("""
                        update user
                        set ticket=%s
                        where username=%s
                        """, val1)
        connect.commit()





    def clickButton_2(self):
        global count
        self.label_2.setText(str(count*50))
        pass

    def clickButton_3(self):
        global count


        self.pushButton_01.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_02.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_03.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_04.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_05.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_06.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_07.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_08.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_09.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_10.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_11.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_12.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_13.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_14.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_15.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_16.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_17.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_18.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_19.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_20.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_21.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_22.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_23.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_24.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_25.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_26.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_27.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_28.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_29.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_30.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_31.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_32.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_33.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_34.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_35.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_36.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_37.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_38.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_39.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_40.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_41.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_42.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_43.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_44.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_45.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_46.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_47.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_48.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_49.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_50.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_51.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_52.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_53.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')

        self.pushButton_54.setStyleSheet(
            '''QPushButton{background:#42E61A;border-radius:5px;}QPushButton:hover{background:green;}''')


        list=[]
        connect = pymysql.connect(host='localhost',  # 本地数据库
                                  user='root',
                                  password='gzy158',
                                  db='课程设计',
                                  charset='utf8')  # 服务器名,账户,密码，数据库名称
        cur = connect.cursor()
        val=(str(userwork.getday()),str(userwork.gettime()))
        print(val)
        cur.execute("""
        select * from seat
        where date=%s and time=%s
        """,val)
        for row in cur.fetchall():
            a=row[2]

        connect.commit()
        list=ast.literal_eval(a)
        print(list)

        if 1 in list:
            self.pushButton_01.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_01.clicked.connect(self.clickButton_01)

        if 2 in list:
            self.pushButton_02.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_02.clicked.connect(self.clickButton_02)

        if 3 in list:
            self.pushButton_03.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_03.clicked.connect(self.clickButton_03)

        if 4 in list:
            self.pushButton_04.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_04.clicked.connect(self.clickButton_04)

        if 5 in list:
            self.pushButton_05.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_05.clicked.connect(self.clickButton_05)

        if 6 in list:
            self.pushButton_06.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_06.clicked.connect(self.clickButton_06)

        if 7 in list:
            self.pushButton_07.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_07.clicked.connect(self.clickButton_07)

        if 8 in list:
            self.pushButton_08.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_08.clicked.connect(self.clickButton_08)

        if 9 in list:
            self.pushButton_09.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_09.clicked.connect(self.clickButton_09)

        if 10 in list:
            self.pushButton_10.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_10.clicked.connect(self.clickButton_10)

        if 11 in list:
            self.pushButton_11.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_11.clicked.connect(self.clickButton_11)

        if 12 in list:
            self.pushButton_12.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_12.clicked.connect(self.clickButton_12)

        if 13 in list:
            self.pushButton_13.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_13.clicked.connect(self.clickButton_13)

        if 14 in list:
            self.pushButton_14.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_14.clicked.connect(self.clickButton_14)

        if 15 in list:
            self.pushButton_15.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_15.clicked.connect(self.clickButton_15)

        if 16 in list:
            self.pushButton_16.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_16.clicked.connect(self.clickButton_16)

        if 17 in list:
            self.pushButton_17.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_17.clicked.connect(self.clickButton_17)

        if 18 in list:
            self.pushButton_18.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_18.clicked.connect(self.clickButton_18)

        if 19 in list:
            self.pushButton_19.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_19.clicked.connect(self.clickButton_19)

        if 20 in list:
            self.pushButton_20.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_20.clicked.connect(self.clickButton_20)

        if 21 in list:
            self.pushButton_21.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_21.clicked.connect(self.clickButton_21)

        if 22 in list:
            self.pushButton_22.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_22.clicked.connect(self.clickButton_22)

        if 23 in list:
            self.pushButton_23.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_23.clicked.connect(self.clickButton_23)

        if 24 in list:
            self.pushButton_24.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_24.clicked.connect(self.clickButton_24)

        if 25 in list:
            self.pushButton_25.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_25.clicked.connect(self.clickButton_25)

        if 26 in list:
            self.pushButton_26.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_26.clicked.connect(self.clickButton_26)

        if 27 in list:
            self.pushButton_27.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_27.clicked.connect(self.clickButton_27)

        if 28 in list:
            self.pushButton_28.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_28.clicked.connect(self.clickButton_28)

        if 29 in list:
            self.pushButton_29.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_29.clicked.connect(self.clickButton_29)

        if 30 in list:
            self.pushButton_30.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_30.clicked.connect(self.clickButton_30)

        if 31 in list:
            self.pushButton_31.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_31.clicked.connect(self.clickButton_31)

        if 32 in list:
            self.pushButton_32.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_32.clicked.connect(self.clickButton_32)

        if 33 in list:
            self.pushButton_33.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_33.clicked.connect(self.clickButton_33)

        if 34 in list:
            self.pushButton_34.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_34.clicked.connect(self.clickButton_34)

        if 35 in list:
            self.pushButton_35.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_35.clicked.connect(self.clickButton_35)

        if 36 in list:
            self.pushButton_36.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_36.clicked.connect(self.clickButton_36)

        if 37 in list:
            self.pushButton_37.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_37.clicked.connect(self.clickButton_37)

        if 38 in list:
            self.pushButton_38.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_38.clicked.connect(self.clickButton_38)

        if 39 in list:
            self.pushButton_39.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_39.clicked.connect(self.clickButton_39)

        if 40 in list:
            self.pushButton_40.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_40.clicked.connect(self.clickButton_40)

        if 41 in list:
            self.pushButton_41.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_41.clicked.connect(self.clickButton_41)

        if 42 in list:
            self.pushButton_42.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_42.clicked.connect(self.clickButton_42)

        if 43 in list:
            self.pushButton_43.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_43.clicked.connect(self.clickButton_43)

        if 44 in list:
            self.pushButton_44.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_44.clicked.connect(self.clickButton_44)

        if 45 in list:
            self.pushButton_45.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_45.clicked.connect(self.clickButton_45)

        if 46 in list:
            self.pushButton_46.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_46.clicked.connect(self.clickButton_46)

        if 47 in list:
            self.pushButton_47.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_47.clicked.connect(self.clickButton_47)

        if 48 in list:
            self.pushButton_48.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_48.clicked.connect(self.clickButton_48)

        if 49 in list:
            self.pushButton_49.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_49.clicked.connect(self.clickButton_49)

        if 50 in list:
            self.pushButton_50.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_50.clicked.connect(self.clickButton_50)

        if 51 in list:
            self.pushButton_51.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_51.clicked.connect(self.clickButton_51)

        if 52 in list:
            self.pushButton_52.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_52.clicked.connect(self.clickButton_52)

        if 53 in list:
            self.pushButton_53.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_53.clicked.connect(self.clickButton_53)

        if 54 in list:
            self.pushButton_54.setStyleSheet(
                '''QPushButton{background:#FF0000;border-radius:5px;}QPushButton:hover{background:red;}''')
        else:
            self.pushButton_54.clicked.connect(self.clickButton_54)