# -*- coding: utf-8 -*-
import ast

import pymysql
# Form implementation generated from reading ui file 'lib/userwork.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import datetime

from PyQt5.QtGui import QStandardItemModel, QStandardItem

day=""
time=""
username=""
def change(a):
    global username
    username=a
def getday():
    return day

def gettime():
    return time
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(954, 829)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(140, 100, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clickbutton)




        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 160, 91, 31))
        self.comboBox.setObjectName("comboBox")

        timelist=[]
        daylist=[]
        day = datetime.date.today()

        for i in range(0, 24, 3):
            time = str(i) + ":00"
            timelist.append(time)
        for i in range(7):
            day = day + datetime.timedelta(days=1)
            daylist.append(str(day))

        self.comboBox.addItems(daylist)





        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 170, 72, 15))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 220, 87, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(timelist)

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 230, 72, 15))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 390, 121, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.clickbutton2)

        self.chapiao = QtWidgets.QTableView(Dialog)
        self.chapiao.setGeometry(QtCore.QRect(30, 460, 256, 261))
        self.chapiao.setObjectName("chapiao")
        self.model = QStandardItemModel(0, 3)
        self.model.setHorizontalHeaderLabels(['日期', '时间', '座位'])
        self.chapiao.setModel(self.model)



        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(450, 540, 91, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(450, 600, 87, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(360, 550, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(360, 610, 72, 15))
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(400, 680, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.clickbutton3)

        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(650, 550, 72, 15))
        self.label_7.setObjectName("label_7")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(740, 600, 87, 31))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(650, 610, 72, 15))
        self.label_8.setObjectName("label_8")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(740, 540, 91, 31))
        self.comboBox_6.setObjectName("comboBox_6")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(710, 680, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.clickbutton4)
        self.pushButton_4.clicked.connect(self.clickbutton3)

        self.comboBox_6.addItems(daylist)
        self.comboBox_5.addItems(timelist)









        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(440, 50, 72, 15))
        self.label_6.setObjectName("label_6")




        connect = pymysql.connect(host='localhost',  # 本地数据库
                                  user='root',
                                  password='gzy158',
                                  db='课程设计',
                                  charset='utf8')  # 服务器名,账户,密码，数据库名称
        cur = connect.cursor()
        user = []
        cur.execute("select * from seat")

        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(340, 80, 556, 292))
        self.tableView.setObjectName("tableView")
        self.model1 = QStandardItemModel(0, 4)
        self.model1.setHorizontalHeaderLabels(['剧名', '日期', '时间','座位数'])
        self.tableView.setModel(self.model1)

        for row in cur.fetchall():

            self.model1.appendRow(
                [QStandardItem(row[4]), QStandardItem(row[0]), QStandardItem(row[1]), QStandardItem(row[3])])
        connect.commit()


        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(750, 40, 72, 15))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "用户"))
        self.pushButton.setText(_translate("Dialog", "订票"))
        self.label.setText(_translate("Dialog", "选择日期"))
        self.label_2.setText(_translate("Dialog", "选择时间"))
        self.pushButton_2.setText(_translate("Dialog", "查询订票信息"))

        self.label_4.setText(_translate("Dialog", "选择日期"))
        self.label_5.setText(_translate("Dialog", "选择时间"))
        self.pushButton_3.setText(_translate("Dialog", "退票"))
        self.label_7.setText(_translate("Dialog", "选择日期"))
        self.label_8.setText(_translate("Dialog", "选择时间"))
        self.pushButton_4.setText(_translate("Dialog", "改票"))
        self.label_6.setText(_translate("Dialog", "推荐影片"))
        self.label_9.setText(_translate("Dialog", "热销影片"))

    def clickbutton(self):
        global day
        global time
        day=str(self.comboBox.currentText())
        time=str(self.comboBox_2.currentText())

    def clickbutton2(self):
        global username
        connect = pymysql.connect(host='localhost',  # 本地数据库
                                  user='root',
                                  password='gzy158',
                                  db='课程设计',
                                  charset='utf8')  # 服务器名,账户,密码，数据库名称
        cur = connect.cursor()


        temp = ""
        cur.execute("""
                                select * from user
                                where username=%s
                                """, username)
        for row in cur.fetchall():
            temp = row[3]
        list1 = ast.literal_eval(temp)

        list2=[]
        for i in list1:

            j=eval(str(i))
            list2.append(j)


        daylist1=[]
        timelist1=[]
        self.model.clear()
        for j in list2:
            daylist1.append(j[0])
            timelist1.append(j[1])
            self.model.appendRow(
                [QStandardItem(j[0]), QStandardItem(j[1]), QStandardItem(j[2])])

        self.comboBox_3.addItems(daylist1)
        self.comboBox_4.addItems(timelist1)






    def clickbutton3(self):
        global username
        connect = pymysql.connect(host='localhost',  # 本地数据库
                                      user='root',
                                      password='gzy158',
                                      db='课程设计',
                                      charset='utf8')  # 服务器名,账户,密码，数据库名称
        cur = connect.cursor()


        temp = ""
        cur.execute("""
                                            select * from user
                                            where username=%s
                                            """, username)
        for row in cur.fetchall():
            temp = row[3]
        list1 = ast.literal_eval(temp)

        list2 = []
        for i in list1:
            j = eval(i)
            list2.append(j)
        print(list2)
        print(list2[0][1])


        #用户删除后还剩的订单
        list3=[]



        for j in list2:
            if (j[0]!=self.comboBox_3.currentText())|(j[1]!=self.comboBox_4.currentText()):
                list3.append(j)
        shanchuan=""
        for j in list2:
            if (j[0]==self.comboBox_3.currentText())&(j[1]==self.comboBox_4.currentText()):
                shanchuan=j[2]
        #用户要删除的座位
        list4=eval(shanchuan)
        print(shanchuan)

        a=str(list3)

        val = (a, username)
        cur.execute("""
                            update user
                            set ticket=%s
                            where username=%s
                            """, val)

        cur.execute("""select * from seat
                       where date=%s and time=%s
                       """, (self.comboBox_3.currentText(),self.comboBox_4.currentText()))

        shenpiao=""
        for row in cur.fetchall():
            shenpiao=row[2]
        #座位中的已经订购的位置
        list5=eval(shenpiao)
        list7=[]
        for i in list5:
            if i not in list4:
                list7.append(i)

        val5=(str(list7),self.comboBox_3.currentText(),self.comboBox_4.currentText())
        cur.execute("""
                                    update seat
                                    set seat=%s
                                    where date=%s and time=%s
                                    """, val5)

        connect.commit()


    def clickbutton4(self):
        global day
        global time
        day=str(self.comboBox_6.currentText())
        time=str(self.comboBox_5.currentText())

